title: Gear Fit Pro
description: Resucita tu Gear Fit
github_username: RenderXor
url: "https://renderxor.github.io/gearfitpro"
baseurl: "gearfitpro"
show_downloads: false

twitter_username: RenderXor

previsualiza: true

markdown: kramdown

theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
