title: Gear Fit Pro
description: Resucita tu Gear Fit
github_username: RenderXor
url: "https://renderxor.hithub.io/gearfitpro"
baseurl: "gearfitpro"
show_downloads: false

post.pre: true

markdown: kramdown

theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
